### ISSUE TITLE
Renaming shape() to extend(), dim() to rank() and uoflow() to options()

### ISSUE THREAD

**Issue by HDembinski** [HDembinski/histogram#112]
Bjørn Reese:

> Related to this, I also like the extent() over shape(). This name is
also used by Boost.MultiArray and the std::mdspan proposal (P0009R7).
In the name of consistency, you may also consider renaming dim() to
rank().

**Comment by jpivarski** [comment]
Even though I want to use this with Numpy, I agree that consistency with Boost is better than consistency with Numpy.
